"""
Markdown backup writer.
Saves all tailored content to markdown files for version control.
Section 11 of spec.md.
"""

import os
from datetime import datetime
from typing import Dict, List


def save_markdown_backup(job: Dict, tailored_resume: str, emails: Dict, cover_letter: str = None) -> str:
    """
    Save tailored resume and emails to markdown file.
    
    Args:
        job: Job dict with metadata
        tailored_resume: Tailored resume text
        emails: Dict with hiring_manager and recruiter email dicts
        cover_letter: Optional cover letter text
    
    Returns:
        Path to saved markdown file
    """
    # Create output directory structure
    date_str = datetime.now().strftime('%Y-%m-%d')
    output_dir = os.path.join('output', date_str)
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate filename
    company = job.get('company', 'Unknown').replace(' ', '-').replace('/', '-')
    title = job.get('title', 'Unknown').replace(' ', '-').replace('/', '-')
    filename = f"{company}_{title}.md"
    filepath = os.path.join(output_dir, filename)
    
    # Build markdown content
    content = _build_markdown(job, tailored_resume, emails, cover_letter)
    
    # Write file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)
    
    return filepath


def _build_markdown(job: Dict, tailored_resume: str, emails: Dict, cover_letter: str = None) -> str:
    """Build markdown document with all content."""
    
    hm = emails['hiring_manager']
    rec = emails['recruiter']
    
    # Build cover letter section if present
    cover_section = ""
    if cover_letter:
        cover_section = f"""
---

## Cover Letter

{cover_letter}
"""
    
    markdown = f"""# {job.get('title', 'Unknown')} at {job.get('company', 'Unknown')}

**Generated:** {datetime.now().strftime('%B %d, %Y at %I:%M %p')}

---

## Job Metadata

- **Title:** {job.get('title', 'Unknown')}
- **Company:** {job.get('company', 'Unknown')}
- **Location:** {job.get('location', 'Unknown')}
- **Source:** {job.get('source', 'Unknown')}
- **URL:** {job.get('url', 'N/A')}
- **Score:** {job.get('score', 'N/A')}/10
- **H1B Status:** {job.get('h1b_flag', 'unknown')}
- **On Target List:** {'Yes' if job.get('on_target_list', False) else 'No'}

---

## Job Description

{job.get('description', 'No description available')}

---

## Tailored Resume

```
{tailored_resume}
```

---

## Cold Email — Hiring Manager

**Subject:** {hm['subject']}

{hm['body']}

---

## Cold Email — Recruiter

**Subject:** {rec['subject']}

{rec['body']}
{cover_section}
---

_Generated by Automated Job Hunter Pipeline_
"""
    
    return markdown


def list_output_files(days: int = 7) -> List[str]:
    """
    List all markdown output files from last N days.
    
    Args:
        days: Number of days to look back
    
    Returns:
        List of file paths
    """
    files = []
    
    if not os.path.exists('output'):
        return files
    
    # Get all date folders
    for date_folder in os.listdir('output'):
        date_path = os.path.join('output', date_folder)
        
        if not os.path.isdir(date_path):
            continue
        
        # List all .md files in this date folder
        for filename in os.listdir(date_path):
            if filename.endswith('.md'):
                filepath = os.path.join(date_path, filename)
                files.append(filepath)
    
    return sorted(files, reverse=True)
